finalyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('authors/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('authors/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('authors/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('books/create/', views.BookCreate.as_view(), name='book_create'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
    path('register/',views.register,name='register'),
    path('results/', views.SearchView.as_view(), name='search'),
    path('request/',views.book_request.as_view() , name='book_request'),
    path('request-sended/<int:pk>',views.RequestDetailView.as_view(),name='request-detail'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finalyear/', include('finalyear.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='finalyear/', permanent=True)),
    path('reset_password/',auth_views.PasswordResetView.as_view(),name='reset_password'),
    path('reset_password_send/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetView.as_view(),name='password_reset_done'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

finalyear/models.py
from django.db import models

from django.urls import reverse
import uuid
from datetime import date
from django.contrib.auth.models import User

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    langs= models.ForeignKey('Language',on_delete=models.SET_NULL,null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    file_url = models.URLField(max_length=1000,null=True)
    download_url=models.URLField(max_length=1000,null=True)
    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['first_name']
        

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}  {self.first_name}'

class Language(models.Model):
    lang=models.CharField(max_length=30)
    class meta:
        ordering=['lang']

    def __str__(self):
        return self.lang

class Request(models.Model):
    book_name=models.CharField(max_length=30)
    class meta:
        ordering=['book_name']

    def __str__(self):
        return self.book_name
    def get_absolute_url(self):
        return reverse('request-detail', args=[str(self.id)])

finalyear/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from finalyear.models import Author,Book,Request
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        c=0
        for a in username:
            if (a.isspace()):
                c=1
        if c:
            raise ValidationError("Username shouldnot contain space")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        SpecialSym=['@','#','&','₹','_']
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')


        if not any(char.isdigit() for char in password2):
            raise ValidationError('Password should have at least one numeric characters') 

        if not any(char.isupper() for char in password2):
            raise ValidationError('Password should have at least one uppercase letter')

        if not any(char.islower() for char in password2):
            raise ValidationError('Password should have at least one lowercase letter')

        if not any(char in SpecialSym for char in password2):
            raise ValidationError('Password should have at least one of the symbols $@#') 

       
        if password1 and password2 and password1 != password2:
            raise ValidationError("Password doesn't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

    

finalyear/views.py
# Create your views here.
from django.shortcuts import render,get_object_or_404,redirect
from django.views import generic
from finalyear.models import Book, Author, Genre ,Language,Request
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm

def index(request):
    num_books = Book.objects.all().count()
    num_authors = Author.objects.count()
    num_langs= Language.objects.count()
    num_genre=Genre.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    
    context = {
        'num_visits': num_visits,
        'num_authors':num_authors,
        'num_langs':num_langs,
        'num_genre':num_genre,
        'num_books':num_books
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    template_name = 'books/my_arbitrary_template_name_list.html'  # Specify
    paginate_by = 10

class AuthorListView(generic.ListView):
    model = Author
    template_name = 'authors/my_arbitrary_template_name_list.html'  # Specify
    paginate_by = 10
    
class BookDetailView(generic.DetailView):
    model = Book
    def book_detail_view(request, primary_key):
        try:
            book = Book.objects.get(pk=primary_key)
        except Book.DoesNotExist:
            raise Http404('Book does not exist')
        
        return render(request, 'finalyear/book_detail.html', context={'book': book})

class AuthorDetailView(generic.DetailView):
    model = Author
    def author_detail_view(request, primary_key):
        try:
            book = Author.objects.get(pk=primary_key)
        except Book.DoesNotExist:
            raise Http404('Author does not exist')
        
        return render(request, 'finalyear/author_detail.html', context={'author': author})

class AuthorCreate(PermissionRequiredMixin ,CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_birth': '05/01/2018'}
    permission_required='can add author'

class AuthorUpdate(PermissionRequiredMixin,UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required='can change author'

class AuthorDelete(PermissionRequiredMixin,DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required='can delete author'

class BookCreate(PermissionRequiredMixin,CreateView):
    model = Book
    fields = '__all__'
    permission_required='can add book'

class BookUpdate(PermissionRequiredMixin,UpdateView):
    model = Book
    fields = ['title', 'author', 'langs', 'summary','isbn','genre','file_url','download_url']
    permission_required='can change book'


class BookDelete(PermissionRequiredMixin,DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required='can delete book'




def register(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            return redirect('login')

    else:
        f = CustomUserCreationForm()

    return render(request, 'finalyear/register.html', {'form': f})



class SearchView(generic.ListView):
    model = Book
    template_name = 'finalyear/search.html'
    context_object_name = 'all_search_results'

    def get_queryset(self):
        result = super(SearchView, self).get_queryset()
        query = self.request.GET.get('search')
        
        if query:
            postresult = Book.objects.filter(title__icontains= query)
            result = postresult
        else:
            result = None
        
        return result



class book_request(LoginRequiredMixin,CreateView):
    model = Request
    fields = '__all__'

class RequestListView(generic.ListView):
    model = Request
    template_name = 'books/my_arbitrary_template_name_list.html'  # Specify
    paginate_by = 15

class RequestDetailView(generic.DetailView):
    model = Request
    def request_detail_view(request, primary_key):
        try:
            book = Request.objects.get(pk=primary_key)
        except Request.DoesNotExist:
            raise Http404('Request does not exist')
        
        return render(request, 'finalyear/request_detail.html')

finalyear/templates/finalyear/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

finalyear/templates/finalyear/author_detail.html
{% extends "base_generic.html" %}
{% block content %}
        <h1> Author :{{ author.first_name}}  {{ author.last_name}} </h1>
	<p>{% if author.date_of_birth %}<strong> Born : </strong>{{author.date_of_birth}} {% endif %} {% if author.date_of_death %} <br> <strong>Died :</strong>{{author.date_of_death}} {% endif %} <br>
	{% if user.is_staff %} <a href="{% url 'author_update'  author.pk %}">  Update Author </a><a style="padding-left:3em;" href="{% url 'author_delete'  author.pk %}">  Delete Author </a></p> {% endif %}
	<div style="margin-left:20px; margin-top:20px;">
		<h3>Books  </h3>
		<div style="margin-top:20px;">
			{% for book in author.book_set.all %}
				<p> <strong> <a href=" {{ book.get_absolute_url }}">{{book.title }}</a> </strong><br> {{book.summary}}<p>
		{% endfor %}
		</div>
	</div>
{% endblock %}

finalyear/templates/finalyear/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

finalyear/templates/finalyear/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name}} , {{author.last_name }} ({{author.date_of_birth}} - {% if author.date_of_death %} {{author.date_of_death}} {% endif %} )</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors.</p>
  {% endif %}       
{% endblock %}

finalyear/templates/finalyear/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book}}  ?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

finalyear/templates/finalyear/book_detail-2.html
{% extends "base_generic.html" %}

{% block content %}

  <h3>{{ book.title }}</h3>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a>
  <strong style="padding-left:5em;">ISBN:</strong> {{ book.isbn }} 
  <strong style="padding-left:3em;">Language:</strong> {{ book.langs }}
  <strong style="padding-left:3em;">Genre:</strong> {{ book.genre.all|join:", " }}
<br>
  <strong>Summary:</strong> {{ book.summary }}</p>
  {% if user.is_authenticated %}
  <div  style="width: 640px; height: 480px; position: relative;">

      <embed src="https://drive.google.com/file/d/1qu6BV_dIy1l5aFNRjEOem4iCCSBRyj3a/preview"   width="640" height="480" type="application/pdf" />


<object width="640" height="480" data="https://drive.google.com/file/d/1qu6BV_dIy1l5aFNRjEOem4iCCSBRyj3a/preview"></object>

      <div style="width: 80px; height: 80px; position: absolute; opacity: 0; right: 0px; top: 0px;">&nbsp;</div>
</div>

  

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!-- Auto width -->
<button onclick="download()"  class="btn"><i class="fa fa-download"></i> Download</button>

<a id="downloadfile" href="{{ book.download_url }}" download hidden></a>
<script>
function download() {
  document.getElementById('downloadfile').click();
  
}
</script>
{% else %}
<p> Please login to access soft copy of this book </p>
{% endif %}
  {% if user.is_staff %}<p> <a href="{% url 'book_update' book.pk %}" > Book Update</a> <a style="padding-left:3em;" href="{% url 'book_delete' book.pk %}"> Book Delete </a> {% endif %} 
  {% endblock %}

finalyear/templates/finalyear/book_detail.html
{% block title %} <title> {{book.title}}</title>{% endblock %}
{% block content %}

  <h3>{{ book.title }}</h3>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a>
  <strong style="padding-left:5em;">ISBN:</strong> {{ book.isbn }} 
  <strong style="padding-left:3em;">Language:</strong> {{ book.langs }}
  <strong style="padding-left:3em;">Genre:</strong> {{ book.genre.all|join:", " }}
<br>
  <strong>Summary:</strong> {{ book.summary }}</p>
  {% if user.is_authenticated %}
  <div  style="width: 640px; height: 480px; position: relative;">

      <iframe src="{{ book.file_url }}"   width="640" height="480" frameborder="0" scrolling="no" seamless=""></iframe>

      <div style="width: 80px; height: 80px; position: absolute; opacity: 0; right: 0px; top: 0px;">&nbsp;</div>
</div>

  

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!-- Auto width -->
<button onclick="download()"  class="btn"><i class="fa fa-download"></i> Download</button>

<a id="downloadfile" href="{{ book.download_url }}" download hidden></a>
<script>
function download() {
  document.getElementById('downloadfile').click();
  
}
</script>
{% else %}
<p> Please login to access soft copy of this book </p>
{% endif %}
  {% if user.is_staff %}<p> <a href="{% url 'book_update' book.pk %}" > Book Update</a> <a style="padding-left:3em;" href="{% url 'book_delete' book.pk %}"> Book Delete </a> {% endif %} 
  {% endblock %}

finalyear/templates/finalyear/book_detailone.html
{% extends "base_generic.html" %}
{% block title %} <title> {{book.title}}</title>{% endblock %}
{% block content %}

  <h3>{{ book.title }}</h3>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a>
  <strong style="padding-left:5em;">ISBN:</strong> {{ book.isbn }} 
  <strong style="padding-left:3em;">Language:</strong> {{ book.langs }}
  <strong style="padding-left:3em;">Genre:</strong> {{ book.genre.all|join:", " }}
<br>
  <strong>Summary:</strong> {{ book.summary }}</p>
  {% if user.is_authenticated %}
  <div  style="width: 640px; height: 480px; position: relative;">

      <iframe src="{{ book.file_url }}"   width="640" height="480" frameborder="0" scrolling="no" seamless=""></iframe>

      <div style="width: 80px; height: 80px; position: absolute; opacity: 0; right: 0px; top: 0px;">&nbsp;</div>
</div>

  

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!-- Auto width -->
<button onclick="download()"  class="btn"><i class="fa fa-download"></i> Download</button>

<a id="downloadfile" href="{{ book.download_url }}" download hidden></a>
<script>
function download() {
  document.getElementById('downloadfile').click();
  
}
</script>
{% else %}
<p> Please login to access soft copy of this book </p>
{% endif %}
  {% if user.is_staff %}<p> <a href="{% url 'book_update' book.pk %}" > Book Update</a> <a style="padding-left:3em;" href="{% url 'book_delete' book.pk %}"> Book Delete </a> {% endif %} 
  {% endblock %}

finalyear/templates/finalyear/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

finalyear/templates/finalyear/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

finalyear/templates/finalyear/register.html
{% extends "base_generic.html" %}

{% block title %}
    <title>Lokallibrary - User Creation </title>
{% endblock %}

{% block content %}

     <div class="login">

         {% if messages %}
            <ul>
		        {% for message in messages %}
        	        <li class="text-danger">{{ message }}</li>
                	{% endfor %}
	{% endif %}
		        <h1>Enter your credentials to create your account.</h1>

		         <form method="post" >
        		     {% csrf_token %}
        		     <table>
                		{{ form.as_table }}
                		 <tr>
                		    	<td></td>
                	    		<td><input type="submit" name="submit" value="Register" /></td>
				
               			</tr>
	             	    </table>
	<P><strong> Note:</strong></p>
				<p>Password should contain atleast one Uppercase,Lowercase,special characters and a symbol e.g. "Student@123"</p>
         		</form>

            	</ul>
     </div>

{% endblock %}

finalyear/templates/finalyear/request_detail.html
{% extends "base_generic.html" %}
{% block content %}
  {% load static %}
	<h2> Your request has been registered.</h2>

	<p> We'll try to update the book as soon as possible
	
	<p> User: <strong>{{user.get_username}}</strong></p>
	<p> Requested book :<strong> {{ request.book_name }}</strong></p>
{% endblock %}

finalyear/templates/finalyear/request_form.html
{% extends "base_generic.html" %}

{% block content %}
<p> Ask for books that you need</p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

finalyear/templates/finalyear/search.html
{% extends "base_generic.html" %}

{% block content %}
   
    {% for book in all_search_results %}
        <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% empty %}
        <h2>No books related to your search found</h2>
	
    {% endfor %}
{% endblock %}